### ISSUE TITLE
IBM Push Notificatio on iOS 10.0 above

### ISSUE THREAD

**Issue by archiedalisay** [ibm-bluemix-mobile-services/bms-samples-swift-hellopush#19]
Registration for Push Notification on iOS was successfuly registered, then once I sent a Push notification,  doesn't have received any notification and try again to send push... No device registered.

**Comment by AnanthaKrish** [comment]
@archiedalisay Hi, Seems like your certificate is invalid. Create a valid certificate and p12 file. 

Follow this Doc - https://console.bluemix.net/docs/services/mobilepush/push_step_1.html#push_step_1_ios

Let me know if you need further assistance .

Thanks.

**Comment by archiedalisay** [comment]
![img_0126 1](https://user-images.githubusercontent.com/21185027/29256031-c3edab46-80d9-11e7-9620-a36147fb1fd9.PNG)
@AnanthaKrish I got still the same issue. Once it registered and try to push notif..no notification received  and for the 2nd time to push notif...no device register
![img_0125 1](https://user-images.githubusercontent.com/21185027/29256029-bbdfb3b8-80d9-11e7-8ef1-d4b0eadb7560.PNG)

**Comment by AnanthaKrish** [comment]
@archiedalisay the problem is with your p12 file that you uploaded to the Bluemix push service. 
Points to remember ,

1. If you are trying to install app from Xcode (Developer mode) use the sandbox certificate and select the sandbox field in Push service configuration tab.

2. If you are trying to install the app through .ipa (Distribution or ad hoc profile) use the production field in Push service configuration tab.

3. To exporting the p12 from the Keychain right click on the certificate (only certificate . No need of private key) and export as p12.

**Comment by archiedalisay** [comment]
@AnanthaKrish Many thanks...it works now!
